server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db
    username: capstone
    password: capstone
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    # Minimal config since we do a consumer factory in code
